config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :friendships

  get 'friendship/my_friends' => 'friendships#my_friends', as: :my_friends

  get 'friendship/my_friends/:id' => 'friendships#grant_request', as: :grant_request

  scope module: 'mission' do
    resources :missions do
      resources :supervisions
      resources :comments
      post 'supervise' => 'supervisions#create', as: :create_supervision
      get 'supervision/:id' => 'supervisions#grant_supervision', as: :grant_supervision
    end

    get 'supervision/my_supervisions' => 'supervisions#my_supervisions', as: :my_supervisions

    get 'mission/mission_board' => 'missions#mission_board', as: :mission_board
    get 'mission/my_missions' => 'missions#my_missions', as: :my_missions
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  validate :check_id_different
  validates :friend_id, presence: true, uniqueness: { scope: :user_id }
  enum accepted: { unaccepted: 0, granted: 1 }

  belongs_to :user, inverse_of: :friendships
  belongs_to :friend, class_name: User.name, inverse_of: :friendships

  private

  def check_id_different
    errors.add(:friend_id, '不能添加自己为好友') if user_id == friend_id
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  load_and_authorize_resource :friendship

  def create
    @target_user = User.find_by_email(friend_info_params[:email])

    if @target_user.nil?
      redirect_to :back, failure: '用户不存在'
    else
      if current_user.friendships.build(friend: @target_user).save
        redirect_to :my_friends, success: '添加好友成功'
      else
        redirect_to :my_friends, failure: '添加好友失败'
      end
    end
  end

  def my_friends
    @friendships = current_user.friendships.granted
    @requests = Friendship.unaccepted.where(friend: current_user)
  end

  def grant_request
    @friendship.granted!
    @friendship.save

    @reverse_friendship = Friendship.new
    @reverse_friendship.user_id = @friendship.friend_id
    @reverse_friendship.friend_id = @friendship.user_id
    @reverse_friendship.granted!
    @reverse_friendship.save

    redirect_to my_friends_path
  end

  private

  def friend_info_params
    params.require(:friend_info).permit(:email)
  end
end

app/controllers/mission/friendships_controller.rb
class Mission::FriendshipsController < Mission::Controller
  def create
    @target_user = User.find_by_email(params[:email])

    unless @target_user.nil?
      @friendship = Friendship.new(user_id: current_user.id, friend_id: @target_user.id)
      @friendship.save
    end

    render 'mission/mission_board'
  end

  def my_friends
    @friendships = current_user.friendships.all
  end

  def grant_request
    @friendship = Friendship.find_by_id(params[:id])
    @friendship.granted!
    @friendship.save
    redirect_to my_friends_path
  end
end

app/views/friendships/_form.html.slim
= simple_form_for :friend_info, url: friendships_path do |f|
  .row
    .col-sm-6
      .input-group
        = f.input :email, label: false, placeholder: '好友邮箱'
        span.input-group-btn
          = f.button :submit, value: '添加'

app/views/friendships/my_friends.html.slim
.col-xs-7.col-sm-3.col-md-2

.col-lg-9.col-md-8.col-sm-7
  h1.page-header
    = "好友管理"
    - unless @friendship.nil?
      - @friendship.errors.full_messages.each do |msg|
        = msg
  .segment-content
    h3.segment-header
      = "好友申请"

    - unless @requests.empty?
      h4
        = "有新的好友申请"
        .row
          br
        .heads-row
        - @requests.each do |request|
          .col-sm-4.well
            .media
              .media-left
                img.media-object.avatar src='pic.jpg'
              .media-body
                - @applicant = User.find_by_id(request.user_id)
                = @applicant.name
                br
                small
                  = @applicant.email
                br
                = link_to '允许', grant_request_path(request.id), class: 'btn btn-primary',
                  data: { confirm: '确定添加好友？'}
          .col-sm-2
    - else
      = "暂时没有新的好友申请"
    .row

    h3.segment-header
      = "添加好友"
    = render "friendships/form"


    h3.segment-header
      = "我的好友"
    - unless @friendships.empty?
      .heads-row
        - @friendships.each do |friendship|
          .col-sm-4.well
            .media
              .media-left
                img.media-object.avatar src='pic.jpg'
              .media-body
                - @friend = User.find_by_id(friendship.friend_id)
                = @friend.name
                br
                small
                  = @friend.email
          .col-sm-2
    - else
      = "暂时没有好友"