config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :friendships

  get 'friendship/my_friends' => 'friendships#my_friends', as: :my_friends

  get 'friendship/my_friends/:id' => 'friendships#grant_request', as: :grant_request

  scope module: 'mission' do
    resources :missions do
      resources :supervisions
      resources :comments
      post 'supervise' => 'supervisions#create', as: :create_supervision
      get 'supervision/:id' => 'supervisions#grant_supervision', as: :grant_supervision
    end

    get 'supervision/my_supervisions' => 'supervisions#my_supervisions', as: :my_supervisions

    get 'mission/mission_board' => 'missions#mission_board', as: :mission_board
    get 'mission/my_missions' => 'missions#my_missions', as: :my_missions
  end
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  enum status: { unfinished: 0, finished: 1 }

  belongs_to :user, inverse_of: :missions
  has_many :supervisions, dependent: :destroy
  has_many :supervisors, through: :supervisions, class_name: User.name
  has_many :comments, as: :commentable, dependent: :destroy, inverse_of: nil
end

app/models/mission/comment.rb
class Mission::Comment < ActiveRecord::Base
  belongs_to :user, inverse_of: :comments
  belongs_to :commentable, polymorphic: true
end

app/models/mission/supervision.rb
class Mission::Supervision < ActiveRecord::Base
  validates :mission_id, presence: true, uniqueness: { scope: :supervisor_id }
  enum accepted: { unaccepted: 0, granted: 1 }

  belongs_to :mission, inverse_of: :supervisions
  belongs_to :supervisor, class_name: User.name, inverse_of: :supervisions
  has_many :comments, as: :commentable, dependent: :destroy, inverse_of: nil
end

app/controllers/mission/comments_controller.rb
class Mission::CommentsController < Mission::Controller
  load_and_authorize_resource :comments,
                              class: Mission::Comment.name,
                              through: :mission,
                              except: :create
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.commentable_type == 'Mission::Supervision'
      @comment.commentable_id = @mission.supervisions.find_by_supervisor_id(current_user).id
    end
    if @comment.save
      redirect_to :back, success: '留言创建成功'
    else
      redirect_to :back, failure: '留言创建失败'
    end
  end

  def comment_params
    params.require(:comment).permit(:commentable_type, :content)
  end
end

app/controllers/mission/controller.rb
class Mission::Controller < ApplicationController
  load_and_authorize_resource :mission
end

app/controllers/mission/friendships_controller.rb
class Mission::FriendshipsController < Mission::Controller
  def create
    @target_user = User.find_by_email(params[:email])

    unless @target_user.nil?
      @friendship = Friendship.new(user_id: current_user.id, friend_id: @target_user.id)
      @friendship.save
    end

    render 'mission/mission_board'
  end

  def my_friends
    @friendships = current_user.friendships.all
  end

  def grant_request
    @friendship = Friendship.find_by_id(params[:id])
    @friendship.granted!
    @friendship.save
    redirect_to my_friends_path
  end
end

app/controllers/mission/missions_controller.rb
class Mission::MissionsController < Mission::Controller
  def my_missions
    @missions = current_user.missions unless current_user.nil?
  end

  def mission_board
    @missions = Mission.order(created_at: :desc).where(user_id:
      [current_user] + current_user.friends)
    render 'mission/mission_board'
  end

  def new
  end

  def edit
  end

  def create
    @mission.user = current_user
    if @mission.save
      redirect_to @mission, success: '任务创建成功'
    else
      render 'new'
    end
  end

  def update
    if @mission.update(mission_params)
      redirect_to @mission
    else
      render 'edit'
    end
  end

  def destroy
    @mission.destroy

    redirect_to :my_missions
  end

  def show
  end

  private

  def mission_params
    params.require(:mission).permit(:target, :description, :deadline)
  end
end

app/controllers/mission/supervisions_controller.rb
class Mission::SupervisionsController < Mission::Controller
  load_and_authorize_resource :supervision, class: Mission::Supervision.name, through: :mission,
                                            except: [:create, :my_supervisions]

  def create
    @supervision = @mission.supervisions.build(supervisor: current_user)

    if @supervision.save
      redirect_to mission_path(@mission), success: '成功发送申请'
    else
      redirect_to mission_path(@mission), alert: '申请失败'
    end
  end

  def show
  end

  def grant_supervision
    if @supervision.granted!
      redirect_to mission_path(@mission), success: '成功接受申请'
    else
      redirect_to mission_path(@mission), alert: '接受申请失败'
    end
  end

  def my_supervisions
    @supervisions = current_user.supervisions
  end
end

app/views/mission/missions/_controls.html.slim
span.pull-right.btn-group
  = link_to('编辑', edit_mission_path(@mission), class: ['btn btn-default']) if can?(:edit, @mission)
  = link_to('删除', mission_path(@mission), method: :delete, class: ['btn btn-danger']) if can?(:delete, @mission)
  = link_to('监督', mission_create_supervision_path(@mission), class: ['btn btn-info'], method: :post) if can?(:supervise, @mission)
  = link_to('确认完成', mission_path(@mission), class: ['btn btn-success']) if can?(:finish, @mission)
  = link_to('返回', :back, class: ['btn btn-warning'])

app/views/mission/missions/_form.html.slim
= simple_form_for @mission  do |f|

  .col-lg-2.col-md-1.col-sm-1

  .col-lg-8.col-md-10.col-sm-11
    = f.error_notification

    = f.input :target, label: '任务目标：'

    = f.input :description, as: :text, label: '任务描述：', input_html: { rows: '10' }

    = f.input :deadline, label: '截止日期：'

    = f.submit '提交', class: ['btn btn-primary']

    .pull-right
      = link_to('返回', back_url, class: ['btn btn-warning'])

app/views/mission/missions/_form_mission.html.slim
= simple_form_for @mission do |f|
  = f.error_notification

  = f.input :target, label: '目标'
  = f.input :description, label: '任务描述'
  = f.input :deadline, label: '截止日期：'

  = f.submit '提交'

app/views/mission/missions/_mission.html.slim
= content_tag_for(:tr, mission) do
    td
    td
      .mission
        .h4
          = link_to(mission.target, mission_path(mission))
    td
      .h5
        = mission.description
    td = mission.deadline
    td
      - if mission.supervisions.granted.any?
        - mission.supervisions.each do |s|
          = s.supervisor.name + " "
      - else
        .h5 = '暂无监督者'
    - if format == "mission_board"
      td = mission.user.name
      td = mission.created_at
    td

app/views/mission/missions/edit.html.slim
= page_header('修改任务: ')

= render partial: 'form', locals: { back_url: mission_path(@mission) }

app/views/mission/missions/my_missions.html.slim
= page_header('我的任务：') do
  = link_to('创建新任务', new_mission_path, class:['btn btn-primary'])

table.table.mission-list.table-hover
  thead
    tr
      th
      th = '目标'
      th = '任务描述'
      th = '截止日期'
      th = '监督人'
      th
  tbody
    - unless @missions.empty?
      = render partial: @missions, locals: {format: "my_missions"}
    - else
      tr
        td colspan="6" align="center"
          h3 = "目前没有任务"

app/views/mission/missions/new.html.slim
= page_header('创建新任务: ')

= render partial: 'form', locals: { back_url: my_missions_path }

app/views/mission/missions/show.html.slim
= page_header(@mission.target) do
  = render 'controls'

- if @mission.unfinished?
  .label.label-default
    = '未完成'
- else
  .label.label-success
    = '已完成'

- if @mission.supervisions.granted.empty?
  .label.label-default
    = '无人监督'
  - if @mission.supervisions.any?
    = '有好友愿意监督你完成这项任务'
    - @mission.supervisions.each do |s|
      h6
        = s.supervisor.name
        span= link_to('接受', mission_grant_supervision_path(@mission, s), class: ['lab btn-info btn-xs'])
- else
  .label.label-warning
    = "监督者："
    - @mission.supervisions.granted.each do |s|
      = s.supervisor.name + " "

.form-horizontal
  .h3 = '目标 :'
  .alert.alert-success
    = @mission.target
  .h3 = '任务描述 :'
  .alert.alert-info
    = @mission.description
  .h3 = '截止日期 :'
  .alert.alert-danger id="time"
    = @mission.deadline