config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :friendships

  get 'friendship/my_friends' => 'friendships#my_friends', as: :my_friends

  get 'friendship/my_friends/:id' => 'friendships#grant_request', as: :grant_request

  scope module: 'mission' do
    resources :missions do
      resources :supervisions
      resources :comments
      post 'supervise' => 'supervisions#create', as: :create_supervision
      get 'supervision/:id' => 'supervisions#grant_supervision', as: :grant_supervision
    end

    get 'supervision/my_supervisions' => 'supervisions#my_supervisions', as: :my_supervisions

    get 'mission/mission_board' => 'missions#mission_board', as: :mission_board
    get 'mission/my_missions' => 'missions#my_missions', as: :my_missions
  end
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  enum status: { unfinished: 0, finished: 1 }

  belongs_to :user, inverse_of: :missions
  has_many :supervisions, dependent: :destroy
  has_many :supervisors, through: :supervisions, class_name: User.name
  has_many :comments, as: :commentable, dependent: :destroy, inverse_of: nil
end

app/models/mission/comment.rb
class Mission::Comment < ActiveRecord::Base
  belongs_to :user, inverse_of: :comments
  belongs_to :commentable, polymorphic: true
end

app/models/mission/supervision.rb
class Mission::Supervision < ActiveRecord::Base
  validates :mission_id, presence: true, uniqueness: { scope: :supervisor_id }
  enum accepted: { unaccepted: 0, granted: 1 }

  belongs_to :mission, inverse_of: :supervisions
  belongs_to :supervisor, class_name: User.name, inverse_of: :supervisions
  has_many :comments, as: :commentable, dependent: :destroy, inverse_of: nil
end

app/models/supervision.rb
class Supervision < ActiveRecord::Base
  validates :mission_id, presence: true, uniqueness: { scope: :supervisor_id }
  enum accepted: { unaccepted: 0, granted: 1 }

  belongs_to :mission, inverse_of: :supervisions
  belongs_to :supervisor, class_name: User.name, inverse_of: :supervisions
end

app/controllers/mission/comments_controller.rb
class Mission::CommentsController < Mission::Controller
  load_and_authorize_resource :comments,
                              class: Mission::Comment.name,
                              through: :mission,
                              except: :create
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.commentable_type == 'Mission::Supervision'
      @comment.commentable_id = @mission.supervisions.find_by_supervisor_id(current_user).id
    end
    if @comment.save
      redirect_to :back, success: '留言创建成功'
    else
      redirect_to :back, failure: '留言创建失败'
    end
  end

  def comment_params
    params.require(:comment).permit(:commentable_type, :content)
  end
end

app/controllers/mission/controller.rb
class Mission::Controller < ApplicationController
  load_and_authorize_resource :mission
end

app/controllers/mission/friendships_controller.rb
class Mission::FriendshipsController < Mission::Controller
  def create
    @target_user = User.find_by_email(params[:email])

    unless @target_user.nil?
      @friendship = Friendship.new(user_id: current_user.id, friend_id: @target_user.id)
      @friendship.save
    end

    render 'mission/mission_board'
  end

  def my_friends
    @friendships = current_user.friendships.all
  end

  def grant_request
    @friendship = Friendship.find_by_id(params[:id])
    @friendship.granted!
    @friendship.save
    redirect_to my_friends_path
  end
end

app/controllers/mission/missions_controller.rb
class Mission::MissionsController < Mission::Controller
  def my_missions
    @missions = current_user.missions unless current_user.nil?
  end

  def mission_board
    @missions = Mission.order(created_at: :desc).where(user_id:
      [current_user] + current_user.friends)
    render 'mission/mission_board'
  end

  def new
  end

  def edit
  end

  def create
    @mission.user = current_user
    if @mission.save
      redirect_to @mission, success: '任务创建成功'
    else
      render 'new'
    end
  end

  def update
    if @mission.update(mission_params)
      redirect_to @mission
    else
      render 'edit'
    end
  end

  def destroy
    @mission.destroy

    redirect_to :my_missions
  end

  def show
  end

  private

  def mission_params
    params.require(:mission).permit(:target, :description, :deadline)
  end
end

app/controllers/mission/supervisions_controller.rb
class Mission::SupervisionsController < Mission::Controller
  load_and_authorize_resource :supervision, class: Mission::Supervision.name, through: :mission,
                                            except: [:create, :my_supervisions]

  def create
    @supervision = @mission.supervisions.build(supervisor: current_user)

    if @supervision.save
      redirect_to mission_path(@mission), success: '成功发送申请'
    else
      redirect_to mission_path(@mission), alert: '申请失败'
    end
  end

  def show
  end

  def grant_supervision
    if @supervision.granted!
      redirect_to mission_path(@mission), success: '成功接受申请'
    else
      redirect_to mission_path(@mission), alert: '接受申请失败'
    end
  end

  def my_supervisions
    @supervisions = current_user.supervisions
  end
end

app/views/mission/supervisions/_controls.html.slim
span.pull-right.btn-group
  = link_to('确认完成', mission_path(@mission), class: ['btn btn-success']) if can?(:finish, @mission)
  = link_to('返回', :back, class: ['btn btn-warning'])

app/views/mission/supervisions/_form_comments.html.slim
= simple_form_for :comment, url: mission_comments_path do |f|
    = f.input :content, placeholder: '请输入内容', label: false
    = f.hidden_field :commentable_type, value: Mission::Supervision
    = f.submit "留言"

app/views/mission/supervisions/_supervision.html.slim
= content_tag_for(:tr, supervision) do
  td
  td
    .mission
      .h4
        = link_to(supervision.mission.target, mission_supervision_path(supervision.mission, supervision))
  td
    .h5
      = supervision.mission.description
  td = supervision.mission.deadline
  td = supervision.mission.user.name
  td = supervision.mission.created_at

app/views/mission/supervisions/_supervisors_list.html.slim
.sidebar-nav-fixed.pull-right.affix
  .well
    ul.nav
      li.nav-header = '监督者'
      - @supervision.mission.supervisors.each do |supervisor|
        li.active
          a href="#"
            = supervisor.name

app/views/mission/supervisions/my_supervisions.html.slim
= page_header('我监督的任务：')

table.table.mission-list.table-hover
  thead
    tr
      th
      th = '目标'
      th = '任务描述'
      th = '截止日期'
      th = '发布者'
      th = '发布日期'
  tbody
    - unless @supervisions.empty?
      = render partial: @supervisions
    - else
      tr
        td colspan="6" align="center"
          h3 = "目前没有监督中的任务"

app/views/mission/supervisions/show.html.slim
.col-sm-9
  = page_header(@mission.target) do
    = render 'controls'
  - if @mission.unfinished?
    .label.label-default
      = '未完成'
  - else
    .label.label-success
      = '已完成'

  .label.label-warning
    = "监督者："
    - @mission.supervisions.granted.each do |s|
      = s.supervisor.name + " "

  .form-horizontal
    .h3 = '目标 :'
    .alert.alert-success
      = @mission.target
    .h3 = '任务描述 :'
    .alert.alert-info
      = @mission.description
    .h3 = '截止日期 :'
    .alert.alert-danger id="time"
      = @mission.deadline
    .h3 = '留言 :'
    .alert.alert-warning
      - if @supervision.comments.any?
        - @supervision.comments.order(created_at: :asc).each do |comment|
          = User.find_by_id(comment.user_id).name + ": "
          span = comment.content
          br
      - else
        = '暂无留言'
      = render 'form_comments'
.col-sm-3
  = render 'supervisors_list'