config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :friendships

  get 'friendship/my_friends' => 'friendships#my_friends', as: :my_friends

  get 'friendship/my_friends/:id' => 'friendships#grant_request', as: :grant_request

  scope module: 'mission' do
    resources :missions do
      resources :supervisions
      resources :comments
      post 'supervise' => 'supervisions#create', as: :create_supervision
      get 'supervision/:id' => 'supervisions#grant_supervision', as: :grant_supervision
    end

    get 'supervision/my_supervisions' => 'supervisions#my_supervisions', as: :my_supervisions

    get 'mission/mission_board' => 'missions#mission_board', as: :mission_board
    get 'mission/my_missions' => 'missions#my_missions', as: :my_missions
  end
end

app/views/layouts/_footer.html.slim
footer class="footer"
  small
    a href="http://railstutorial.org/"
    | Rails Tutorial
    < by Michael Hartl

    nav
      ul
        li = link_to "About",   '#'
        li = link_to "Contact", '#'
        li
          a href="http://news.railstutorial.org/" News

app/views/layouts/_form_add_friend.html.slim
= form_for :friendship, url: friendships_path do |f|
  = f.label "添加好友"
  = f.text_field :email, :value => "邮箱地址"
  = f.submit("发送申请")

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-inverse"
  div class="navbar-inner"
    div clas="container"
      = link_to "sample app", "#", id: "logo"
      nav
        ul class="nav pull-right"
          li = link_to "Home",    missionsystem_main_path
          li = link_to "Help",    missionsystem_help_path
          li = link_to "About",   missionsystem_about_path

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = 'FuzzyNinja'
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    = viewport_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    nav.navbar.navbar-default.navbar-fixed-top id = "mainNav"
      div.container-fluid
        div.navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only
              = "Toggle navigation"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand.page-scroll href="#page-top"
            = "Fuzzy Ninja"

        div.collapse.navbar-collapse id="bs-example-navbar-collapse-1"
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                a.page-scroll href=root_path
                  = "主页"
              li
                a.page-scroll href=my_missions_path
                  = "To Do List"
              li
                a.page-scroll href="#blog"
                  = "Blog"
              li
                a.dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                  => current_user.name
                  span.caret
                  ul.dropdown-menu.dropdown-menu-right
                    li = link_to("我的好友", my_friends_path)
                    li = link_to('退出登录', destroy_user_session_path, method: :delete)
            - else
              li
                a.page-scroll href=new_user_registration_path
                  = "注册"
              li
                a.page-scroll href=new_user_session_path
                  = "登录"

    header

    div.mypage
      = yield

    div.footer
      div.container
        div.row
          div.col-sm-4
            div.widget
              h4.title
                |  友情链接
              div.content.friend-links
                a[href="#"]
                  | Link
          div.col-sm-4
            div.widget
              h4.title
                |  关于我们
              div.content.about-us
                a[href="#"]
                  | ONE
                a[href="#"]
                  | TWO
                a[href="#"]
                  | THREE
                a[href="#"]
                  | FOUR
          div.col-sm-4
            div.widget
              h4.title
                |  此条待定
              div.content.to-be-developed
                a[href="#"]
                  | To Be Developed
      div.website-info
        span
          |  A Personal Website
        span
          |  |
        span
          |  Just For Fun

app/views/layouts/index.html.slim
doctype html
html
  head
    title
      = 'FuzzyNinja'
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    = viewport_meta_tag
    = stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'index', 'data-turbolinks-track' => true
    = csrf_meta_tags

  = yield

  div.footer
    div.container
      div.row
        div.col-sm-4
          div.widget
            h4.title
              |  友情链接
            div.content.friend-links
              a[href="#"]
                | Link
        div.col-sm-4
          div.widget
            h4.title
              |  关于我们
            div.content.about-us
              a[href="#"]
                | ONE
              a[href="#"]
                | TWO
              a[href="#"]
                | THREE
              a[href="#"]
                | FOUR
        div.col-sm-4
          div.widget
            h4.title
              |  此条待定
            div.content.to-be-developed
              a[href="#"]
                | To Be Developed
    div.website-info
      span
        |  A Personal Website
      span
        |  |
      span
        |  Just For Fun

app/views/layouts/mission.html.slim
= extends :application do
  .container
    .row
      .col-xs-7.col-sm-3.col-md-2
        .sidebar-nav.panel.panel-default
          .panel-heading
            i.glyphicon.glyphicon-th-list
            = " 任务系统"
          .list-group
            a.list-group-item href= mission_board_path
              i.glyphicon.glyphicon-list-alt
              = " 任务板"
            a.list-group-item href= my_missions_path
              i.glyphicon.glyphicon-pencil
              = " 我的任务"
              i.badge.badge-info = "1"
            a.list-group-item href= my_supervisions_path
              i.glyphicon.glyphicon-eye-open
              = " 我监督的任务 "
              i.badge.badge-info = "2"

      .col-lg-9.col-md-8.col-sm-7
        = yield